### ISSUE TITLE
Z order in fullscreen

### ISSUE THREAD

**Issue by kyrylo-pshenychnyi** [canonical/ubuntu-frame-osk#75]
Hello, 

Recently I encountered an interesting behavior connected with the OSK on Ubuntu. 

When a fullscreen window with an input filed is reparented into another window - OSK loses Z order at some point. 

In my testing, I reparent Chromium fullscreen window into a simple X Window (the '_NET_WM_STATE_FULLSCREEN' atom is set). After a while Z order of the OSK is violated. Please, see the attached video. 
Any help is highly appreciated 

https://github.com/canonical/ubuntu-frame-osk/assets/45938288/7f8d138b-910a-40b7-bfe9-aabebbd62b34

**Comment by Saviq** [comment]
@kyrylo-pshenychnyi are you using Ubuntu Frame? And the ubuntu-frame-osk snap?

It's unclear if what's popping up there is actually the OSK you've reported the bug on…

**Comment by kyrylo-pshenychnyi** [comment]
@Saviq I am using the default Ubuntu OSK. Is it the Ubuntu Frame?

**Comment by Saviq** [comment]
Default Ubuntu OSK is GNOME's, so no.

You'll want to report the bug with `ubuntu-bug gnome-shell`.
